### ISSUE TITLE
Cannot query the dataset example

### ISSUE THREAD

**Issue by bpavie** [ome/ome-zarr-py#105]
Dear,

I cannot query the test dataset described in the documentation:

```
ome_zarr info https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/
ERROR:ome_zarr.cli:not a zarr: None
```

**Comment by joshmoore** [comment]
Hi @bpavie. Which version of ome-zarr do you have installed? If the latest, can you try running with `ome_zarr -vvv info ...` and see what errors it shows?

**Comment by bpavie** [comment]
Hi @joshmoore 

Thanks for your quick answer, 

I installed the ome-zarr  version 0.0.21

Here is the result of the query with the `-vvv` :
```
ome_zarr -vvv info https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/
DEBUG:asyncio:Using selector: SelectSelector
DEBUG:fsspec.http:https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/
DEBUG:ome_zarr.format:Created nested FSStore(https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/, r, {'dimension_separator': '/', 'normalize_keys': True})
DEBUG:fsspec.http:https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/.zarray
DEBUG:fsspec.http:https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/.zgroup
ERROR:ome_zarr.cli:not a zarr: None
```

**Comment by joshmoore** [comment]
And what version of fsspec?

**Comment by bpavie** [comment]
fsspec version 2021.7.0

If it can help, the query works if I switch the server address from `https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/` to `https://idr-s3.openmicroscopy.org/idr/zarr/v0.1/6001240.zarr/` as suggested in https://forum.image.sc/t/mirroring-idr-zarr-datasets/41136/9

**Comment by joshmoore** [comment]
I can confirm I'm seeing the same thing with fsspec 2021.7.0

<details><summary>error</summary>

```
(z) ~ $ome_zarr info https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/
ERROR:ome_zarr.io:503, message='Service Unavailable', url=URL('https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/.zarray')
Traceback (most recent call last):
  File "/opt/ome-zarr-py/ome_zarr/io.py", line 147, in get_json
    data = self.__store.get(subpath)
  File "/usr/local/anaconda3/envs/z/lib/python3.9/_collections_abc.py", line 678, in get
    return self[key]
  File "/Users/jamoore/opt/zarr/zarr/storage.py", line 1119, in __getitem__
    return self.map[key]
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/mapping.py", line 133, in __getitem__
    result = self.fs.cat(k)
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/asyn.py", line 88, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/asyn.py", line 69, in sync
    raise result[0]
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/asyn.py", line 344, in _cat
    raise ex
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/implementations/http.py", line 222, in _cat_file
    self._raise_not_found_for_status(r, url)
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/implementations/http.py", line 207, in _raise_not_found_for_status
    response.raise_for_status()
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 503, message='Service Unavailable', url=URL('https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/.zarray')
ERROR:ome_zarr.io:503, message='Service Unavailable', url=URL('https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/.zgroup')
Traceback (most recent call last):
  File "/opt/ome-zarr-py/ome_zarr/io.py", line 147, in get_json
    data = self.__store.get(subpath)
  File "/usr/local/anaconda3/envs/z/lib/python3.9/_collections_abc.py", line 678, in get
    return self[key]
  File "/Users/jamoore/opt/zarr/zarr/storage.py", line 1119, in __getitem__
    return self.map[key]
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/mapping.py", line 133, in __getitem__
    result = self.fs.cat(k)
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/asyn.py", line 88, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/asyn.py", line 69, in sync
    raise result[0]
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/asyn.py", line 344, in _cat
    raise ex
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/implementations/http.py", line 222, in _cat_file
    self._raise_not_found_for_status(r, url)
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/fsspec/implementations/http.py", line 207, in _raise_not_found_for_status
    response.raise_for_status()
  File "/usr/local/anaconda3/envs/z/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 503, message='Service Unavailable', url=URL('https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/.zgroup')
ERROR:ome_zarr.cli:not a zarr: None
(z) ~ $curl https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/.zgroup
{
    "zarr_format": 2
```

</details>

I was previously on 2021.4.0 though I believe that 2021.6.0 should work as well.

cc: @martindurant

**Comment by martindurant** [comment]
Fixed in https://github.com/intake/filesystem_spec/pull/726 - but it's *weird*!

**Comment by joshmoore** [comment]
Heh. Thanks, @martindurant.

**Comment by joshmoore** [comment]
@bpavie: I'm assuming that you were able to use a different version of fsspec to get things working. If not, let us know.
