### ISSUE TITLE
Cannot find HCS well on Windows

### ISSUE THREAD

**Issue by ziw-liu** [ome/ome-zarr-py#323]
As of v0.8.2, ome-zarr-py cannot read [HCS dataset](https://zenodo.org/records/8091756/files/20200812-CardiomyocyteDifferentiation14-Cycle1.zarr.zip) stored on the local disk of a Window PC:

```py
>>> from ome_zarr.io import parse_url
>>> from ome_zarr.reader import Reader
>>> reader = Reader(parse_url("20200812-CardiomyocyteDifferentiation14-Cycle1.zarr"))
>>> next(reader())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\ome_zarr\reader.py", line 621, in __call__
    node = Node(self.zarr, self)
  File "C:\...\lib\site-packages\ome_zarr\reader.py", line 58, in __init__
    self.specs.append(Plate(self))
  File "C:\...\lib\site-packages\ome_zarr\reader.py", line 473, in __init__
    self.get_pyramid_lazy(node)
  File "C:\...\lib\site-packages\ome_zarr\reader.py", line 498, in get_pyramid_lazy
    raise Exception("Could not find first well")
Exception: Could not find first well
```

#322 seems to fix this too.

**Comment by will-moore** [comment]
#322 has been merged and released now. Happy to close this?

**Comment by ziw-liu** [comment]
> #322 has been merged and released now. Happy to close this?

@will-moore Just tested that it works now. Thanks!
